export {
  getTeams,
  getTeamById,
  createTeam,
  updateTeam,
  deleteTeam,
  getTrainees,
  getTraineeById,
  createTrainee,
  updateTrainee,
  getStagesByTrainee,
  createStage,
  updateStage,
  getColorBlindTests,
  createColorBlindTest,
  getMeetings,
  createMeeting,
  updateMeeting,
  getResignations,
  createResignation,
  batchCreateStagesAndMeetings,
} from './tqc';
