export {
  useNewTQCStore,
  useNewTQCTeams,
  useNewTQCTrainees,
  useNewTQCSelectedTrainee,
  useNewTQCMeetings,
  useNewTQCUpcomingMeetings,
  useNewTQCResignations,
  useNewTQCResignationAnalysis,
  useNewTQCDashboardStats,
  useNewTQCHrType3Employees,
  useNewTQCLoading,
  useNewTQCError,
  useNewTQCTraineeFilters,
  useNewTQCMeetingFilters,
  useNewTQCResignationFilters,
  useNewTQCActions,
} from './newTqc';
