import type { ReportField } from './types';

export const AVAILABLE_FIELDS: Record<string, ReportField[]> = {
  employees: [
    { key: 'employee_id', label: 'report.fields.employee_id', type: 'string', source: 'employees' },
    { key: 'employee_name', label: 'report.fields.employee_name', type: 'string', source: 'employees' },
    { key: 'department', label: 'report.fields.department', type: 'enum', source: 'employees' },
    { key: 'position', label: 'report.fields.position', type: 'enum', source: 'employees' },
    { key: 'building', label: 'report.fields.building', type: 'enum', source: 'employees' },
    { key: 'line', label: 'report.fields.line', type: 'string', source: 'employees' },
    { key: 'hire_date', label: 'report.fields.hire_date', type: 'date', source: 'employees' },
    { key: 'status', label: 'report.fields.status', type: 'enum', source: 'employees' },
    { key: 'updated_at', label: 'report.fields.updated_at', type: 'date', source: 'employees' },
  ],

  training_programs: [
    { key: 'program_code', label: 'report.fields.program_code', type: 'string', source: 'training_programs' },
    { key: 'program_name', label: 'report.fields.program_name', type: 'string', source: 'training_programs' },
    { key: 'program_name_vn', label: 'report.fields.program_name_vn', type: 'string', source: 'training_programs' },
    { key: 'program_name_kr', label: 'report.fields.program_name_kr', type: 'string', source: 'training_programs' },
    { key: 'category', label: 'report.fields.category', type: 'enum', source: 'training_programs' },
    { key: 'target_positions', label: 'report.fields.target_positions', type: 'string', source: 'training_programs' },
    { key: 'evaluation_type', label: 'report.fields.evaluation_type', type: 'enum', source: 'training_programs' },
    { key: 'passing_score', label: 'report.fields.passing_score', type: 'number', source: 'training_programs', aggregatable: true },
    { key: 'duration_hours', label: 'report.fields.duration_hours', type: 'number', source: 'training_programs', aggregatable: true },
    { key: 'validity_months', label: 'report.fields.validity_months', type: 'number', source: 'training_programs', aggregatable: true },
    { key: 'training_level', label: 'report.fields.training_level', type: 'enum', source: 'training_programs' },
    { key: 'training_type', label: 'report.fields.training_type', type: 'enum', source: 'training_programs' },
    { key: 'is_active', label: 'report.fields.is_active', type: 'boolean', source: 'training_programs' },
    { key: 'created_at', label: 'report.fields.created_at', type: 'date', source: 'training_programs' },
    { key: 'updated_at', label: 'report.fields.updated_at', type: 'date', source: 'training_programs' },
  ],

  training_results: [
    { key: 'result_id', label: 'report.fields.result_id', type: 'string', source: 'training_results' },
    { key: 'session_id', label: 'report.fields.session_id', type: 'string', source: 'training_results' },
    { key: 'employee_id', label: 'report.fields.employee_id', type: 'string', source: 'training_results' },
    { key: 'program_code', label: 'report.fields.program_code', type: 'string', source: 'training_results' },
    { key: 'training_date', label: 'report.fields.training_date', type: 'date', source: 'training_results' },
    { key: 'score', label: 'report.fields.score', type: 'number', source: 'training_results', aggregatable: true },
    { key: 'grade', label: 'report.fields.grade', type: 'enum', source: 'training_results' },
    { key: 'result', label: 'report.fields.result', type: 'enum', source: 'training_results' },
    { key: 'needs_retraining', label: 'report.fields.needs_retraining', type: 'boolean', source: 'training_results' },
    { key: 'evaluated_by', label: 'report.fields.evaluated_by', type: 'string', source: 'training_results' },
    { key: 'remarks', label: 'report.fields.remarks', type: 'string', source: 'training_results' },
    { key: 'test_attempt', label: 'report.fields.test_attempt', type: 'number', source: 'training_results', aggregatable: true },
    { key: 'trainer_name', label: 'report.fields.trainer_name', type: 'string', source: 'training_results' },
    { key: 'created_at', label: 'report.fields.created_at', type: 'date', source: 'training_results' },
    { key: 'updated_at', label: 'report.fields.updated_at', type: 'date', source: 'training_results' },
  ],

  training_sessions: [
    { key: 'session_id', label: 'report.fields.session_id', type: 'string', source: 'training_sessions' },
    { key: 'program_code', label: 'report.fields.program_code', type: 'string', source: 'training_sessions' },
    { key: 'session_date', label: 'report.fields.session_date', type: 'date', source: 'training_sessions' },
    { key: 'session_time', label: 'report.fields.session_time', type: 'string', source: 'training_sessions' },
    { key: 'trainer_name', label: 'report.fields.trainer_name', type: 'string', source: 'training_sessions' },
    { key: 'trainer', label: 'report.fields.trainer', type: 'string', source: 'training_sessions' },
    { key: 'location', label: 'report.fields.location', type: 'string', source: 'training_sessions' },
    { key: 'max_attendees', label: 'report.fields.max_attendees', type: 'number', source: 'training_sessions', aggregatable: true },
    { key: 'status', label: 'report.fields.status', type: 'enum', source: 'training_sessions' },
    { key: 'training_level', label: 'report.fields.training_level', type: 'enum', source: 'training_sessions' },
    { key: 'training_type', label: 'report.fields.training_type', type: 'enum', source: 'training_sessions' },
    { key: 'notes', label: 'report.fields.notes', type: 'string', source: 'training_sessions' },
    { key: 'created_by', label: 'report.fields.created_by', type: 'string', source: 'training_sessions' },
    { key: 'created_at', label: 'report.fields.created_at', type: 'date', source: 'training_sessions' },
  ],

  certificates: [
    { key: 'certificate_id', label: 'report.fields.certificate_id', type: 'string', source: 'certificates' },
    { key: 'certificate_number', label: 'report.fields.certificate_number', type: 'string', source: 'certificates' },
    { key: 'employee_id', label: 'report.fields.employee_id', type: 'string', source: 'certificates' },
    { key: 'employee_name', label: 'report.fields.employee_name', type: 'string', source: 'certificates' },
    { key: 'department', label: 'report.fields.department', type: 'enum', source: 'certificates' },
    { key: 'position', label: 'report.fields.position', type: 'enum', source: 'certificates' },
    { key: 'program_code', label: 'report.fields.program_code', type: 'string', source: 'certificates' },
    { key: 'program_name', label: 'report.fields.program_name', type: 'string', source: 'certificates' },
    { key: 'training_date', label: 'report.fields.training_date', type: 'date', source: 'certificates' },
    { key: 'score', label: 'report.fields.score', type: 'number', source: 'certificates', aggregatable: true },
    { key: 'grade', label: 'report.fields.grade', type: 'enum', source: 'certificates' },
    { key: 'issue_date', label: 'report.fields.issue_date', type: 'date', source: 'certificates' },
    { key: 'issued_by', label: 'report.fields.issued_by', type: 'string', source: 'certificates' },
    { key: 'status', label: 'report.fields.status', type: 'enum', source: 'certificates' },
    { key: 'created_at', label: 'report.fields.created_at', type: 'date', source: 'certificates' },
  ],

  tqc_trainees: [
    { key: 'trainee_id', label: 'report.fields.trainee_id', type: 'string', source: 'tqc_trainees' },
    { key: 'employee_id', label: 'report.fields.employee_id', type: 'string', source: 'tqc_trainees' },
    { key: 'employee_name', label: 'report.fields.employee_name', type: 'string', source: 'tqc_trainees' },
    { key: 'team_id', label: 'report.fields.team_id', type: 'string', source: 'tqc_trainees' },
    { key: 'department', label: 'report.fields.department', type: 'enum', source: 'tqc_trainees' },
    { key: 'position', label: 'report.fields.position', type: 'enum', source: 'tqc_trainees' },
    { key: 'building', label: 'report.fields.building', type: 'enum', source: 'tqc_trainees' },
    { key: 'line', label: 'report.fields.line', type: 'string', source: 'tqc_trainees' },
    { key: 'hire_date', label: 'report.fields.hire_date', type: 'date', source: 'tqc_trainees' },
    { key: 'training_status', label: 'report.fields.training_status', type: 'enum', source: 'tqc_trainees' },
    { key: 'start_date', label: 'report.fields.start_date', type: 'date', source: 'tqc_trainees' },
    { key: 'expected_end_date', label: 'report.fields.expected_end_date', type: 'date', source: 'tqc_trainees' },
    { key: 'actual_end_date', label: 'report.fields.actual_end_date', type: 'date', source: 'tqc_trainees' },
    { key: 'created_at', label: 'report.fields.created_at', type: 'date', source: 'tqc_trainees' },
    { key: 'updated_at', label: 'report.fields.updated_at', type: 'date', source: 'tqc_trainees' },
  ],
};

export const getAvailableFields = (source: string): ReportField[] => {
  return AVAILABLE_FIELDS[source] || [];
};
